In [52]:
import numpy as np
import matplotlib.pyplot as plt

In [53]:
def sigmoid(z):
    h_x = 1/(1+np.e**(-z))
    return h_x

In [54]:
def compute_cost(x,y,theta):
    m = y.shape[0]
    z = np.dot(x,theta)
    g = sigmoid(z)
    J_theta = (-1/m)* (np.sum(y*np.log(g) + (1-y)*np.log(1-g)))
    
    grad = (1/m)*((np.dot(x.T,g) - np.dot(x.T,y)).T)
    
    return J_theta,grad

In [55]:
data = np.loadtxt('ex2data1.txt',delimiter=',')
x = data[:,:2]
y = data[:,-1]

m = y.shape[0]
X = np.concatenate((np.ones((m,1)),x),axis = 1)
n = X.shape[1]
theta = np.zeros((n,1))

iters = 1500
learning_rate = 0.1

J,grad = compute_cost(X,y,theta)
print(J)
print(grad)

69.31471805599453
[[ -0.1         32.22213703  32.51099904]
 [-44.33135362 -12.00921659 -11.72035457]
 [-43.87384125 -11.55170422 -11.26284221]]
